### ISSUE TITLE
Formatting problem

### ISSUE THREAD

**Issue by sandyvern** [learn-co-curriculum/keyword-args-mass-assignment#15]
I think there is an issue with the formatting of this lesson...the last half of it is not formatted as normal. I believe it may be because the last section of text is incorporated in the first quiz question. Maybe an extra space after the first quiz question will help it.  Also the last question is not formatted correctly either...again possibly all due to the fact that it thinks that whole section is part of the first question.

**Comment by AnnJohn** [comment]
hi @sandyvern this actually looks fine on our end. Could you post a screenshot of what you see?

**Comment by sandyvern** [comment]
Hi @AnnJohn That's weird...it all looks fine now?!? When I saw it from the first quiz question down looked like it was all just straight text...you could see the hash symbols for the headings...no code boxes etc.  But looks fine now...sorry! If I see something like that again I will know to take a screenshot.

**Comment by AnnJohn** [comment]
not a problem at all @sandyvern! we also updated our quiz formatting so you most likely did see an error but it got fixed! thank you for raising the issue!
