### ISSUE TITLE
Quiz prompt vs. solution is confusing 

### ISSUE THREAD

**Issue by MatthewKrey-zz** [learn-co-curriculum/keyword-args-mass-assignment#2]
Yesterday we were asked for feedback on aspects of the Learn product, including the quizzes. Below is a good example of an opportunity for improvement to the Quiz feature of Learn: 

If you try good form by dropping into IRB and messing around with this exercise on your own first, you will find that you can arrive at the correct solution. However, if you enter the solution into the Quiz text box, following the prompt to "#leave the below line alone!", you are marked incorrect! 

<img width="733" alt="screen shot 2015-08-08 at 2 26 40 pm" src="https://cloud.githubusercontent.com/assets/10355200/9151690/015b930c-3dda-11e5-94ac-e6a63d81a6d6.png">

If you "See Solution" after banging your head against the wall a few times: 

<img width="643" alt="screen shot 2015-08-08 at 2 27 13 pm" src="https://cloud.githubusercontent.com/assets/10355200/9151693/0ec7cfc4-3dda-11e5-8fdd-71a5c087248a.png">

and try to re-enter the solution: 

<img width="680" alt="screen shot 2015-08-08 at 2 36 13 pm" src="https://cloud.githubusercontent.com/assets/10355200/9151717/e27a3eec-3dda-11e5-97b0-1af1fa19b198.png">

You are marked incorrect again. 

Overall the quizzes are great, and they feel like they should help reinforce the learning of the idea more quickly by not having to fork/clone/add/commit/push/pull a simple lab and should help save time, energy and GitHub Repo space - but when they cause you trouble like this it feels more like an obstacle than a learning tool (unless you are trying to reinforce improving the product by submitting new issues).

**Comment by AnnJohn** [comment]
@MatthewKrey it looks like in your argument, you have an extra "the" which explains the error. You don't need the "the" since train_line say "the B train" . Changing the syntax should fix the problem.
