### ISSUE TITLE
The correct answer is missing punctuation

### ISSUE THREAD

**Issue by regilfillan** [learn-co-curriculum/keyword-args-mass-assignment#20]
def rat_counter(rat_count:, train_line:)
  "There are #{rat_count} rats on the #{train_line}"
end

Should have ...#{train_line}`.`"

**Comment by maxwellbenton** [comment]
Hi @regilfillan,

We've corrected the typos in the quiz answers you pointed out, which should resolve this issue.

Thank you for opening this issue and providing feedback!
