### ISSUE TITLE
Quiz giving error

### ISSUE THREAD

**Issue by mystycs** [learn-co-curriculum/keyword-args-mass-assignment#8]
I am trying to submit code on the quiz, and i even submitted what the solution code is an i get this return error. "syntax error, unexpected tIDENTIFIER"

This is for the first quiz in the assignment.

![errorrrrr](https://cloud.githubusercontent.com/assets/3004566/12590482/3815d19a-c431-11e5-81cc-e3bed6593c13.PNG)

**Comment by deniznida** [comment]
@mystycs thanks for raising this issue. the syntax error was fixed
